version: "3.7"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      Postgres_DB: "productsapi"
    ports:
      - "5432:5432"
    
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: on-failure
    depends_on:
      - "postgres"
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_DATABASE: "productsapi"
      DB_HOST: "postgres" 
  
  
    


