version: "3.3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: service
    restart: always
    volumes:
      - /app/node_modules

  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - /app/dump.sql:/docker-entrypoint-initdb.d/


